Resources:
   Ec2Instance:
      Type: AWS::EC2::Instance
      Properties:
        InstanceType: t2.micro
        ImageId: ami-009d6802948d06e52
        KeyName: "MyEC2Web"  
        Tags:
          - Key: Name
            Value: Middleware

            
